### ISSUE TITLE
How to get Apple/Google Pay to show up in the payment options in the new payment element...

### ISSUE THREAD

**Issue by rchrdnsh** [joshnuss/svelte-stripe-js#15] opened 2021-12-07 20:40 UTC
Hi Josh! XD

I noticed in the new stripe payment element that they have multiple payment options available to choose from on top:

<img width="1130" alt="Screen Shot 2021-12-07 at 12 37 56 PM" src="https://user-images.githubusercontent.com/7884263/145102806-01c398a6-999a-480f-a72b-1c181db6c3e3.png">

...but your demo page does not seem have that working ATM...just curious how that might be set up to work in the library.

thank you again :-)

**Comment by joshnuss** [comment] 2021-12-07 20:41
Hey Richard!

Can you try running the demo page on localhost? I think it's because GooglePay/ApplePay require the TLD be `localhost` for test-mode. Should work find for production mode (assuming the domain is registered with Apple)

**Comment by rchrdnsh** [comment] 2021-12-07 20:43
oh, ok, I'll try to do that today and let you know :-)

**Comment by rchrdnsh** [comment] 2021-12-07 21:06
ok, trying to get it up and running and I am currently getting the following error, which I do not understand:

```bash
You did not provide an API key. You need to provide your API key in the Authorization header, using Bearer auth (e.g. 'Authorization: Bearer YOUR_SECRET_KEY'). See https://stripe.com/docs/api#authentication for details, or we can help at https://support.stripe.com/.
Error: You did not provide an API key. You need to provide your API key in the Authorization header, using Bearer auth (e.g. 'Authorization: Bearer YOUR_SECRET_KEY'). See https://stripe.com/docs/api#authentication for details, or we can help at https://support.stripe.com/.
    at res.toJSON.then.StripeAPIError.message (/Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/stripe/lib/StripeResource.js:214:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Unexpected token E in JSON at position 0
SyntaxError: Unexpected token E in JSON at position 0
    at JSON.parse (<anonymous>)
    at Proxy.<anonymous> (file:///Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/@sveltejs/kit/dist/ssr.js:1030:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async load (stripe-test.svelte:11:35)
    at async load_node (file:///Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/@sveltejs/kit/dist/ssr.js:1058:12)
    at async respond$1 (file:///Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/@sveltejs/kit/dist/ssr.js:1264:15)
    at async render_page (file:///Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/@sveltejs/kit/dist/ssr.js:1454:19)
    at async resolve (file:///Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/@sveltejs/kit/dist/ssr.js:1717:10)
    at async respond (file:///Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/@sveltejs/kit/dist/ssr.js:1696:10)
    at async svelteKitMiddleware (file:///Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/@sveltejs/kit/dist/chunks/index.js:4557:22)
```

...not sure what to change, but here is the current code that I have basically copied and pasted from your example:

```svelte
<script context='module'>
  export async function load({ fetch }) {
    // create payment intent
    const response = await fetch('/api/payment-intent', {
      method: 'POST',
      headers: {
        'content-type': 'application/json'
      },
      body: JSON.stringify({amount: 1000})
    })
    const { clientSecret } = await response.json()
    // share payment intent's client secret
    return {
      props: {
        clientSecret
      }
    }
  }
</script>

<script>
  import { goto } from '$app/navigation'
  import { onMount } from 'svelte'
  import { loadStripe } from '@stripe/stripe-js'
  import { PaymentElement } from 'svelte-stripe-js'
  export let clientSecret
  let stripe = null
  let error = null
  let elements
  let processing = false
  onMount(async () => {
    stripe = await loadStripe(import.meta.env.VITE_STRIPE_PUBLIC_KEY)
  })
  async function submit() {
    // avoid processing duplicates
    if (processing) return
    processing = true
    // confirm payment with stripe
    const result = await stripe
      .confirmPayment({
        elements,
        redirect: 'if_required'
      })
    // log results, for debugging
    console.log({result})
    if (result.error) {
      // payment failed, notify user
      error = result.error
      processing = false
    } else {
      // payment succeeded, redirect to "thank you" page
      goto('/thanks')
    }
  }
</script>

<h1>Payment Element Example</h1>
{#if error}
  <p class=error>{error.message} Please try again.</p>
{/if}
{#if stripe}
  <form on:submit|preventDefault={submit}>
    <PaymentElement {stripe} {clientSecret} bind:elements/>
    <button>Pay</button>
  </form>
{:else}
  Loading...
{/if}
```

...and:

```js
import Stripe from 'stripe'

const stripe = new Stripe(process.env['STRIPE_SECRET_KEY'])

export async function post() {
  const paymentIntent = await stripe.paymentIntents.create({
    amount: 1000,
    currency: 'usd',
    automatic_payment_methods: {
      enabled: true,
    }
  })

  return {
    body: {
      clientSecret: paymentIntent.client_secret
    }
  }
}
```

...and I copied my test keys into my .env file and am running `dotenv 10.0.0` as a dependency...

**Comment by joshnuss** [comment] 2021-12-07 21:17
Are you prefixing your `pnpm run dev` command with `dotenv` cli?
Like this: https://github.com/joshnuss/svelte-stripe-js/blob/1d3cd8c90462e1c4908c660c9eb67134ec8331be/package.json#L7

And I think you should run it with the `--http`, ie `pnpm run dev -- --https`

**Comment by joshnuss** [comment] 2021-12-07 21:18
Maybe add some `console.log()` to print out the env var to make sure its picking it up.

```javascript
import Stripe from 'stripe'

console.log(process.env['STRIPE_SECRET_KEY'])

const stripe = new Stripe(process.env['STRIPE_SECRET_KEY'])

```

**Comment by rchrdnsh** [comment] 2021-12-07 21:24
yeah, it's coming back `undefined` for me...

I also was not doing anything at all with dotenv...

also, why is there a p in front of npm??? Is this a new version of npm or something?

**Comment by rchrdnsh** [comment] 2021-12-07 21:26
k, lloking at your `package.json` and you have `dotenv-cli` in you dev deps instead `dotenv` in your deps...also, a bunch of commends...this is probably where I am a bit lost, lol :-)

**Comment by joshnuss** [comment] 2021-12-07 21:32
`pnpm` is an alternative to `npm`, it's is a bit faster, but either would work.

You'll need to install `dotenv-cli` for the cli version of `dotenv`.

By prefixed your `svelte-kit dev` with the `dotenv` command, it will load all the variables in your `.env` file before executing the command `svelte-kit dev`.

It's not needed in production, because your host (vercel, etc..) will be setting the environment variables for you.

**Comment by rchrdnsh** [comment] 2021-12-07 21:51
hmmmm...so, I did this in my package.json:

```json
{
  "name": "rykr-kit",
  "version": "0.0.1",
  "scripts": {
    "dev": "dotenv -- svelte-kit dev",
    "build": "svelte-kit build",
    "preview": "svelte-kit preview"
  },
  "devDependencies": {
    "@agentofuser/rehype-section": "^1.0.5",
    "@emotion/is-prop-valid": "^1.1.1",
    "@sindresorhus/slugify": "^2.1.0",
    "@stripe/stripe-js": "^1.21.2",
    "@sveltejs/adapter-netlify": "next",
    "@sveltejs/kit": "next",
    "dotenv-cli": "^4.1.1",
    "github-slugger": "^1.4.0",
    "mdast-util-to-string": "^3.1.0",
    "mdsvex": "^0.9.8",
    "rehype-add-classes": "^1.0.0",
    "rehype-autolink-headings": "^6.1.0",
    "rehype-slug": "^5.0.0",
    "rehype-urls": "^1.1.1",
    "remark-abbr": "^1.4.1",
    "remark-sectionize": "^1.1.1",
    "sparticles": "^1.3.0",
    "stripe": "^8.191.0",
    "svelte": "^3.44.2",
    "svelte-media": "^0.1.5",
    "svelte-motion": "^0.11.2",
    "svelte-stripe-js": "^0.0.8",
    "unist-util-visit": "^4.0.0",
    "vite-imagetools": "^3.6.8"
  },
  "type": "module"
}
```

and then I run this command: `npm run dev -- --https`

and I get this in chrome:

<img width="762" alt="Screen Shot 2021-12-07 at 1 50 55 PM" src="https://user-images.githubusercontent.com/7884263/145111595-5ee0475f-cf47-4757-9949-583490b4d25e.png">

see anything I might be missing?

**Comment by joshnuss** [comment] 2021-12-07 22:09
Are you using `http://localhost` or `https://localhost`

When passing `--https` it means it will generate a certificate and run on `https://` 

All this should be in the docs, so it's good you're doing a run through

**Comment by rchrdnsh** [comment] 2021-12-07 22:25
da heck??? so, I explicitly types in https and got......this?!?!?!??

<img width="991" alt="Screen Shot 2021-12-07 at 2 23 55 PM" src="https://user-images.githubusercontent.com/7884263/145115346-80d748f3-271b-40ef-a9fd-e1b0039d1e6a.png">

ummmmm...any thoughts? XD

**Comment by rchrdnsh** [comment] 2021-12-07 22:29
hmmmm...so i found a way to click through to the stripe page i'm building, but still same errors.... secret keys in kit seem kinda tough...le sigh...

**Comment by joshnuss** [comment] 2021-12-07 22:29
oh, maybe you need to add the vite extension to generate an SSL certificate

```bash
npm install -D vite-plugin-mkcert
```

then add the plugin to your `svelte.config.js`

```javascript
import mkcert from 'vite-plugin-mkcert'

const config = {
 
  kit: {
    // ....

    vite: {
      server: {
        https: true,
      },
      plugins: [ mkcert.default({hosts: ['localhost', 'app.local']}) ]
    }
  }
}

export default config
```

Also, you should bump `svelte-stripe-js` to `0.0.9` to get the `<PaymentElement/>` component

**Comment by joshnuss** [comment] 2021-12-07 22:32
I would break the problem down:

 you can eliminate svelte-kit, and just test that dotenv is working

```
npx dotenv -- node
```

That will open the node console, then run `process.env.STRIPE_SECRET_KEY` to see if it's there

**Comment by joshnuss** [comment] 2021-12-07 22:34
Also, check the var name in your .env, if you copied it from the docs there was a typo.
The two keys should be:

```
VITE_STRIPE_PUBLIC_KEY=pk_test_...
STRIPE_SECRET_KEY=sk_test_...
```

**Comment by rchrdnsh** [comment] 2021-12-08 00:48
AHHHHHHHHHHHHHHHHHHH!!!!
.
I DID EVERYTHING AND NOTHING WAS WORKING AND I WAS LOSING MY MIND AHHHHH!!!
.
.
.
.
.
.

...and it was the typo....
.
.
.
.
.
😑
.
.
.
.
.
😅😂🤣
.
.
.
.
.
yay :-)


Thank you very much for your help and patience Josh XD

**Comment by rchrdnsh** [comment] 2021-12-08 00:52
ok, now to work on the apple and google pay buttons showing up and changing the theme :-)

**Comment by rchrdnsh** [comment] 2021-12-08 01:02
Huzzzzaaaahhhhh!!!!
<img width="506" alt="Screen Shot 2021-12-07 at 5 01 55 PM" src="https://user-images.githubusercontent.com/7884263/145129815-fed181ba-80c7-46c1-9efd-533a27d5b4f7.png">

**Comment by joshnuss** [comment] 2021-12-08 01:24
Ahh, nice! Glad we tracked it down. 
And thanks for testing the docs. Much appreciated!

I see it's not showing GooglePay/ApplePay.. are you on Safari or Chrome? Do you have GooglePay / ApplyPay enabled?

To change the theme:

```html
<PaymentElement theme="light"/>
```

**Comment by rchrdnsh** [comment] 2021-12-08 01:35
Yeah, got the theme working...will work on making custom themes next...

As far as resting the Apple Pay button, I was using safari with Apple Pay enabled, so...you know...I dunno 🤷🏼‍♂️

**Comment by joshnuss** [comment] 2021-12-08 01:50
I can confirm GooglePay works in test-mode with https://localhost, but I don't have any Apple devices to test ApplePay.

According to this article: https://clementsauvage.medium.com/testing-apple-pay-on-the-web-with-stripe-99499427e147
> Stripe allows us to test its service without SSL, but Apple requires it. First, SSL on localhost is not that easy, moreover, you can’t use self-signed certificates… That’s really annoying! I definitely don’t pay to pay €10 for testing something

So the issue looks like it's with the certificate, you would need a real certificate to test in localhost.

It might be easier to just push the app to a free host like Vercel, which will create a certificate, and then configure add that domain name in Stripe's dashboard

![image](https://user-images.githubusercontent.com/4437/145134089-c23788c9-6700-453e-a08e-e4be7b9bad1e.png)

**Comment by rchrdnsh** [comment] 2021-12-08 02:29
hmmmmm...k, gonna research this a bit more then, thanks :-)

**Comment by rchrdnsh** [comment] 2021-12-08 02:44
ooooh, how do i pass in the variables?

**Comment by rchrdnsh** [comment] 2021-12-08 02:45
I can confirm that google pay is working for me as well, so that is good :-)

**Comment by joshnuss** [comment] 2021-12-08 02:53
> how do i pass in the variables?

Which variables you referring to?

**Comment by rchrdnsh** [comment] 2021-12-08 04:40
apologies, the variables for custom theming in the docs from this page:

https://stripe.com/docs/stripe-js/appearance-api

**Comment by joshnuss** [comment] 2021-12-08 10:12
oh, i see, 

`<PaymentElement>` accepts [`variables` as a prop](https://github.com/joshnuss/svelte-stripe-js/blob/466ba44f2cf9d974a0dc43ccc049553675486696/src/lib/PaymentElement.svelte#L8), example:

```html
<PaymentElement theme="flat" variables={{colorPrimary: '#0570de', colorBackground: '#ffffff'}}/>
```

**Comment by rchrdnsh** [comment] 2021-12-09 02:10
I was looking at your `PaymentElement` component and it looks like you might need to add the `rules` to it here:

```js
  export let stripe
  export let clientSecret
  export let theme = 'stripe'
  export let variables = {}
  export let rules = {}
  export let elements = isServer ? null : stripe.elements({ appearance: { theme, variables, rules }, clientSecret })
```

...or something along those lines, maybe?

**Comment by joshnuss** [comment] 2021-12-09 02:12
Yep, exactly!

Fixed in 4d13eab9d296b3a389ec38397083bdb7137369d7,
Bump your version of `svelte-stripe-js` to `0.0.10`

**Comment by rchrdnsh** [comment] 2021-12-09 02:13
oh, noyce! thank you :-)

**Comment by joshnuss** [comment] 2021-12-09 02:22
Welcome! Thanks again for test driving it.

And LMK if find any other issues. Once this issue closes I can probably safely bump the version to `0.1`

**Comment by rchrdnsh** [comment] 2021-12-09 17:57
hmmmm...just found something else...trying to switch themes, and my first attempt...not so worked :-)

I tried this:

```
<script>
  import { theme } from '$lib/theme/theme.js';
</script>

<PaymentElement
  {stripe}
  {clientSecret}
  bind:elements
  theme={$theme === 'light' ? lightAppearance.theme : darkAppearance.theme}
  variables={$theme === 'light' ? lightAppearance.variables : darkAppearance.variables}
  rules={$theme === 'light' ? lightAppearance.rules : darkAppearance.rules}
/>
```
...so should that have worked? Could it work in the future? Is there a different and/or better way to switch themes in your estimation?

Thank you in advance...again :-)

**Comment by joshnuss** [comment] 2021-12-09 18:45
It's because the element is created in `onMount()`, so it uses the options that were initially set.

There should be a reactive statement that detects if options change (variables, rules, theme, or label) and update the element.
Do you want to open a PR for this? or I can handle it in a couple days

**Comment by joshnuss** [comment] 2021-12-14 02:42
Hi Richard,

Looked into this a bit. 

Stripe's elements API lets us set styling when the component is mounted. To change the style after mounting, you'd need to re-create a new set of components with the new style. 

The challenge is what to do if those inputs contain a value (eg someone starts typing their card number, and switches to dark mode), if this library automatically recreates the components, we could lose the users state.

If you are OK with potentially losing state, you can force re-mounting using Svelte `#key` directive. The `#key` directive will re-mount all children when it's value changes.

Example:

```html
<script>
  import { theme } from '$lib/theme/theme.js';
</script>

{#key $theme} 
  <PaymentElement
    {stripe}
    {clientSecret}
    bind:elements
    theme={$theme === 'light' ? lightAppearance.theme : darkAppearance.theme}
    variables={$theme === 'light' ? lightAppearance.variables : darkAppearance.variables}
    rules={$theme === 'light' ? lightAppearance.rules : darkAppearance.rules}
  />
{/key}
```

**Comment by joshnuss** [comment] 2021-12-18 00:46
Hi @rchrdnsh,

Let me know your thoughts about this one :slightly_smiling_face:

**Comment by joshnuss** [comment] 2021-12-21 16:00
Hi Richard,

I think the solution I suggested should work. I'm closing the issue for now. Feel free to re-open or open a new issue if you find anything else.

And thanks for reporting these issues! It's improved the docs and code quite a bit and makes it easier for the next person to pick this up. :v:

**Closed by joshnuss** 2021-12-21 16:00 UTC
